[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for production
[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://dealsmarket.netlify.app"
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_ENV = "production"

# Preview deployments
[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_ENV = "preview"

# Development
[context.dev.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_APP_ENV = "development"
